apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: disk-volume
          mountPath: /data
      volumes:
        - name: "disk-volume"
          flexVolume:
            driver: "alicloud/disk"
            fsType: "ext4"
            options:
              volumeType: "alicloud-disk-essd"
              volumeSize: "100Gi" #create disk dynamically when no volumeId given, this feature is only for ECI pod.
